title: Cayman theme
description: My name is Sadaf Tariq. I am an aspiring Data Analyst. Working with data and finding patterns and trends is what I love. I translate data into valuable and comprehensive insights. I want to help others to make right decisions, data-driven decisions. I use Excel, SQL, Python and Power BI and data visualization techniques to present the result. In this page I have added few projects which I did during my training and certification. 

show_downloads: False
#google_analytics:
theme: jekyll-theme-cayman
